name: deploy_frontend
# Deploys when a push is made from the frontend folder

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # List the frontend endpoints for your Azure Front Door
    - name: List Frontend Endpoints
      run: |
        front_door_name="front-door-1"
        resource_group="Resume-RG-JulianPerez"
        endpoints=$(az network front-door frontend-endpoint list --resource-group $resource_group --front-door-name $front_door_name --query "[].name" --output tsv)
        echo "Frontend Endpoints: $endpoints"
      id: list_frontend_endpoints

    - name: Purge CDN Cache for Frontend Endpoints
      uses: azure/CLI@v1
      with:
        inlineScript: |
          for endpoint in ${{ steps.list_frontend_endpoints.outputs.endpoints }}; do
            az network front-door frontend-endpoint purge-endpoint --resource-group $resource_group --front-door-name $front_door_name --name $endpoint
          done
      env:
        resource_group: Resume-RG-JulianPerez
        front_door_name: front-door-1

  # Azure logout
    - name: logout
      run: |
        az logout
      if: always()
